services:
  - type: web
    name: food-delivery-go
    env: go
    rootDir: server
    plan: free
    buildCommand: go build -o server ./cmd/server
    startCommand: ./server
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: MONGODB_CONNECTION_STRING
        sync: false
      - key: AUTH0_ISSUER_BASE_URL
        sync: false
      - key: AUTH0_AUDIENCE
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_API_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 7000
